FROM python:3.12.11-alpine3.22

ARG G2P_REF=develop

RUN apk add --no-cache --virtual .build-deps gcc libc-dev linux-headers make \
 && apk add --no-cache bash git gettext libpq-dev libmagic

WORKDIR /app

# Dynamic deps from workflow (optional)
COPY adapters.requirements.txt /tmp/adapters.requirements.txt
RUN if [ -s /tmp/adapters.requirements.txt ]; then pip install --no-cache-dir -r /tmp/adapters.requirements.txt; fi

# Core libs (as in your current API Dockerfile)
RUN pip install --no-cache-dir git+https://github.com/openg2p/openg2p-fastapi-common@1.1\#subdirectory=openg2p-fastapi-common  \
 && pip install --no-cache-dir git+https://github.com/openg2p/openg2p-fastapi-common@v1.1.4\#subdirectory=openg2p-fastapi-auth

# Always from openg2p-g2p-bridge repo (no local installs)
RUN pip install --no-cache-dir \
    "git+https://github.com/openg2p/openg2p-gen2-master-data@${G2P_REF}"

RUN apk del --no-network .build-deps

ENV PYTHONUNBUFFERED=1
ENV GEN2_MASTER_DATA_API_WORKER_TYPE=gunicorn
ENV GEN2_MASTER_DATA_API_HOST=0.0.0.0
ENV GEN2_MASTER_DATA_API_PORT=8000
ENV GEN2_MASTER_DATA_API_NO_OF_WORKERS=8

# Use module path for migrate and Gunicorn WSGI app
CMD python3 -m openg2p_gen2_master_data.main migrate; \
    ${GEN2_MASTER_DATA_API_WORKER_TYPE} "openg2p_gen2_master_data.main:app" --workers ${GEN2_MASTER_DATA_API_NO_OF_WORKERS} --worker-class uvicorn.workers.UvicornWorker --bind ${GEN2_MASTER_DATA_API_HOST}:${GEN2_MASTER_DATA_API_PORT}